package com.yuanman.app.ui.theme

import androidx.compose.ui.graphics.Color

// 浅色主题色彩
val md_theme_light_primary = Color(0xFF1B5E20)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA6F5A3)
val md_theme_light_onPrimaryContainer = Color(0xFF002204)
val md_theme_light_secondary = Color(0xFF386A20)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFB8F397)
val md_theme_light_onSecondaryContainer = Color(0xFF072100)
val md_theme_light_tertiary = Color(0xFFB06000)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDDB8)
val md_theme_light_onTertiaryContainer = Color(0xFF2B1700)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF7FBF2)
val md_theme_light_onBackground = Color(0xFF181D17)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF181D17)
val md_theme_light_surfaceVariant = Color(0xFFE2E3DC)
val md_theme_light_onSurfaceVariant = Color(0xFF444843)
val md_theme_light_outline = Color(0xFF747972)

// 深色主题色彩
val md_theme_dark_primary = Color(0xFF8BD88A)
val md_theme_dark_onPrimary = Color(0xFF00390A)
val md_theme_dark_primaryContainer = Color(0xFF005313)
val md_theme_dark_onPrimaryContainer = Color(0xFFA6F5A3)
val md_theme_dark_secondary = Color(0xFF9DD67E)
val md_theme_dark_onSecondary = Color(0xFF133800)
val md_theme_dark_secondaryContainer = Color(0xFF225109)
val md_theme_dark_onSecondaryContainer = Color(0xFFB8F397)
val md_theme_dark_tertiary = Color(0xFFFFB86F)
val md_theme_dark_onTertiary = Color(0xFF4A2800)
val md_theme_dark_tertiaryContainer = Color(0xFF693C00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDDB8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF10140F)
val md_theme_dark_onBackground = Color(0xFFE1E4DC)
val md_theme_dark_surface = Color(0xFF171B16)
val md_theme_dark_onSurface = Color(0xFFE1E4DC)
val md_theme_dark_surfaceVariant = Color(0xFF444843)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C8C0)
val md_theme_dark_outline = Color(0xFF8E928B)

// 记账特定语义色
val ExpenseColorLight = Color(0xFFE53935)
val ExpenseColorDark = Color(0xFFEF5350)
val IncomeColorLight = Color(0xFF2E7D32)
val IncomeColorDark = Color(0xFF66BB6A)
val BalanceColorLight = Color(0xFF0288D1)
val BalanceColorDark = Color(0xFF29B6F6)
